dist: focal

language: python

jobs:
  include:
    - stage: publish
      python: '3.11'
      services: []
      addons:
        firefox: 'skip'
        apt: []
      install:
        - nvm install 18
        - npm install semantic-release@20.x.x semantic-release-replace-plugin@1.x.x
      script:
        - npx semantic-release
      deploy:
        provider: pypi
        skip_cleanup: true
        username: $PYPI_USERNAME
        password: $PYPI_PASSWORD
        on:
          branch: master
